name: cv-tutorial
# channels can be picky
# usually best practice to get pytorch from the pytorch channel
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - scikit-learn
  - pip
  # - pip:
  #   - transformers==4.28.0
  #   - datasets
  #   - openpyxl
